import {useId,useState} from 'react';
import {pathways} from '../../data/pathways';
import {sources} from '../../data/sources';
export default function PathwayDiagram({kind='feedback'}:{kind?:string}){
 const pathway=pathways[kind] || pathways.feedback;const [selected,setSelected]=useState(0);const id=useId();
 return <figure className="pathway-figure"><div className="figure-heading"><span className="eyebrow">BIOLOGICAL SYSTEM</span><span className="concept-label">Conceptual model</span></div><h3>{pathway.title}</h3>
 <div className="diagram-scroll" tabIndex={0} aria-label="Scrollable pathway diagram"><svg viewBox={`0 0 ${pathway.nodes.length*156} 110`} style={{minWidth:pathway.nodes.length*125}} role="img" aria-labelledby={id}><title id={id}>{pathway.nodes.map(n=>n.title).join(' → ')}{pathway.loop?' → feedback':''}</title>{pathway.nodes.map((n,i)=><g key={n.title}><rect x={i*156+3} y="12" width="139" height="64" rx="8" fill={selected===i?'var(--accent-soft)':'var(--surface)'} stroke={selected===i?'var(--accent)':'var(--border)'}/><text x={i*156+15} y="32" fontSize="10" fill="var(--accent)">{String(i+1).padStart(2,'0')}</text><text x={i*156+15} y="54" fontSize="11" fill="var(--text)">{n.title}</text>{i<pathway.nodes.length-1 && <path d={`M${i*156+143} 44h13m-5-4 5 4-5 4`} fill="none" stroke="var(--accent)"/>}</g>)}{pathway.loop && <path d={`M${pathway.nodes.length*156-86} 82v18H73V82m-4 5 4-5 4 5`} fill="none" stroke="var(--muted)" strokeDasharray="3 4"/>}</svg></div>
 <div className="step-buttons" role="group" aria-label="Explore pathway steps">{pathway.nodes.map((n,i)=><button key={n.title} aria-pressed={selected===i} onClick={()=>setSelected(i)}>{i+1}. {n.title}</button>)}</div><p className="step-detail" aria-live="polite"><strong>{pathway.nodes[selected].title}.</strong> {pathway.nodes[selected].detail}</p>
 <details><summary>Read every step</summary><ol>{pathway.nodes.map(n=><li key={n.title}><strong>{n.title}.</strong> {n.detail}</li>)}</ol></details><figcaption>{pathway.note} <a href={`/sources#${pathway.source}`}>Source: {sources[pathway.source].organization}</a></figcaption></figure>;
}
