import {useId,useState} from 'react';
import {datasets} from '../../data/datasets';
import {sources} from '../../data/sources';
export default function ResearchChart({dataset='prevalence'}:{dataset?:string}){
 const data=datasets[dataset];const [table,setTable]=useState(false);const id=useId();if(!data)return <p>Dataset unavailable. No values have been substituted.</p>;
 const max=Math.ceil(Math.max(...data.points.map(p=>p.value))/5)*5;const isLine=dataset==='prevalence';
 return <figure className="research-chart"><div className="figure-heading"><span className="eyebrow">SOURCED DATA · {data.unit}</span><button className="text-button" onClick={()=>setTable(!table)} aria-expanded={table}>{table?'Hide':'Show'} data table</button></div><h3>{data.title}</h3><p>{data.measure}</p><svg viewBox="0 0 600 285" role="img" aria-labelledby={id}><title id={id}>{data.title}: {data.points.map(p=>`${p.label}, ${p.value}${data.unit}`).join('; ')}</title>{[0,1,2,3,4].map(t=><g key={t}><line x1="58" x2="560" y1={230-t*48} y2={230-t*48} stroke="var(--border)"/><text x="44" y={234-t*48} textAnchor="end" fill="var(--muted)" fontSize="11">{Math.round(max*t/4*10)/10}</text></g>)}{isLine&&<path d={`M150 ${230-data.points[0].value/max*192}L460 ${230-data.points[1].value/max*192}`} stroke="var(--accent)" strokeWidth="2" strokeDasharray="6 5" fill="none"/>}{data.points.map((p,i)=>{const x=150+i*310,y=230-p.value/max*192;return <g key={p.label}>{isLine?<circle cx={x} cy={y} r="5" fill="var(--accent)"/>:<rect x={x-58} y={y} width="116" height={230-y} rx="3" fill={i===0?'var(--accent)':'var(--muted)'} opacity={i===0?1:.55}/>}<text x={x} y={y-12} textAnchor="middle" fontSize="16" fontWeight="600" fill="var(--text)">{p.value}{data.unit}</text><text x={x} y="256" textAnchor="middle" fontSize="12" fill="var(--muted)">{p.label}</text></g>;})}</svg>
 <div hidden={!table}><table><caption>{data.population}</caption><thead><tr><th>Observation</th><th>{data.unit}</th></tr></thead><tbody>{data.points.map(p=><tr key={p.label}><td>{p.label}</td><td>{p.value}</td></tr>)}</tbody></table></div><noscript><p>{data.points.map(p=>`${p.label}: ${p.value}${data.unit}`).join('; ')}</p></noscript><figcaption><strong>Population:</strong> {data.population}. {data.limitations}<br/><a href={`/sources#${data.sourceId}`}>Source: {sources[data.sourceId].organization} ({sources[data.sourceId].year})</a></figcaption></figure>;
}
